[package]
name = "oracle_test"
version = "0.1.0"
edition = "2021"

[dependencies]
schnorr_fun = "0.10.0"
rand = "0.8.5"
sha2 = "0.10.8"
bitcoin = "0.32.4"
anyhow = "1.0.90"
uuid = { version = "1.11.0", features = ["v4"] }
